# This is a basic workflow to help you get started with Actions

name: update github page

env:
  access: restricted
  registry: https://npm.pkg.github.com
  scope: public-oss
  token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

on:
  schedule:
    - cron: "0 * * * *"
  workflow_call:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "${{env.registry}}"
          scope: "@${{env.scope}}"
      - name: Clear
        run: |
          npm cache clean -f
          rm -rf package *.tgz
          ls -la
      - name: Download belegerfassung
        env:
          NODE_AUTH_TOKEN: ${{env.token}}
        run: |
          npm pack @${{env.scope}}/th-ik-ja-belegerfassung
          ls -la
      - name: Unpack belegerfassung
        run: |
          tar -xzvf public-oss-*.tgz
          rm -rf docs/th-ik-ja-belegerfassung
          mv package/dist docs/th-ik-ja-belegerfassung
          rm -rf package *.tgz
          ls -la
      - name: Download consumption
        env:
          NODE_AUTH_TOKEN: ${{env.token}}
        run: |
          npm pack @${{env.scope}}/general-tracking-of-own-consumption
          ls -la
      - name: Unpack consumption
        run: |
          tar -xzvf public-oss-*.tgz
          rm -rf docs/general-tracking-of-own-consumption
          mv package/dist docs/general-tracking-of-own-consumption
          rm -rf package *.tgz
          ls -la

      - name: Download sudoku
        env:
          NODE_AUTH_TOKEN: ${{env.token}}
        run: |
          npm pack @${{env.scope}}/kolibri-sudoku-solver
          ls -la
      - name: Unpack sudoku
        run: |
          tar -xzvf public-oss-*.tgz
          rm -rf docs/kolibri-sudoku-solver
          mv package/dist docs/kolibri-sudoku-solver
          rm -rf package *.tgz
          ls -la
      - name: Commit changed files
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git status
          git commit -m "Auto update github page"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
